version: "3"

services:
  app:
    container_name: transport-dev
    image: transport-dev
    build:
      context: .
      # target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3047:3000